<a href="https://colab.research.google.com/github/aishwaryabit1603/Big_data/blob/main/lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy
1. Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5]) )
2. Compare the following numpy arrays: arr1 = np.array([[1, 2], [3, 4]])
 arr2 = np.array([[1, 2], [3, 4]])
3. Find the most frequent value and their indice(s) in the following arrays:
i. x = np.array([1,2,3,4,5,1,2,1,1,1])
ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])
4. For the array gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]'),
find i. Sum of all elements
ii. Sum of all elements row-wise
iii. Sum of all elements column-wise

In [3]:
import numpy as np
import random

In [5]:
# 1
arr = np.array([1, 2, 3, 6, 4, 5])
print(arr[::-1])
print(arr[-1::-1])

[5 4 6 3 2 1]
[5 4 6 3 2 1]


In [6]:
# 2
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
print(arr1 == arr2)

comparison = arr1 == arr2
print(comparison)

# checks if all elements in boolean are true or not
print(comparison.all())

print(np.greater(arr1,arr2))
print(np.greater_equal(arr1,arr2))

print(np.less(arr1,arr2))
print(np.less_equal(arr1,arr2))

[[ True  True]
 [ True  True]]
[[ True  True]
 [ True  True]]
True
[[False False]
 [False False]]
[[ True  True]
 [ True  True]]
[[False False]
 [False False]]
[[ True  True]
 [ True  True]]


In [14]:
# 3
x = np.array([1,2,3,4,5,1,2,1,1,1])
unique_x,count_x = np.unique(x,return_counts=True)

# now we will find index of in count_x array where count is max
freq = np.argmax(count_x)
print("X = ",x)
print(unique_x[freq]," with max count of ",count_x[freq])

y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
unique_y,count_y = np.unique(y,return_counts=True)
freq2 = np.argmax(count_y)
print("\nY = ",y)
print(unique_y[freq2]," with max count of ",count_y[freq2])

X =  [1 2 3 4 5 1 2 1 1 1]
1  with max count of  5

Y =  [1 1 1 2 3 4 2 4 3 3]
1  with max count of  3


In [20]:
# 4
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
print("Sum of all Elements : ",gfg.sum())

# 0 - columns
print("Sum of all Elements column wise : ",gfg.sum(axis=0))

# 1 - row
print("Sum of all Elements Rowise wise : ")
print(gfg.sum(axis=1))

Sum of all Elements :  45
Sum of all Elements column wise :  [[20  9 16]]
Sum of all Elements column wise : 
[[14]
 [16]
 [15]]
